# Generated by Django 5.2.7 on 2026-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisCommentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('commentaire', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LaPriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeHadj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeJeun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PasHadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('commentaire', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('reponse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TroisTestament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
    ]
