# Generated by Django 5.2.7 on 2026-02-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ma_Religion_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrandSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('priorite', models.IntegerField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Preche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='audios/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='commentaire',
            new_name='question',
        ),
    ]
